### ISSUE TITLE
Issue with ManagedIndentityCredential

### ISSUE THREAD

**Issue by mikewop** [JDetmar/NLog.Extensions.AzureStorage#133]
We're using AppService deployed in Microsoft Azure, .NET 6.0

Getting this error after upgrading NLog.Extensions.AzureStorage from version 3.2.0 to version 4.0

`
2022-12-01 21:15:17.5645 Error AzureBlobStorageTarget: Failed to initialize blob=2022-12/MyApplication.log in container=api-general-logs Exception: Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Content:

Headers:
Date: Thu, 01 Dec 2022 21:15:16 GMT
Server: Kestrel
Transfer-Encoding: chunked
X-CORRELATION-ID: REDACTED
Content-Type: application/json; charset=utf-8

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
 ---> Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Content:

Headers:
Date: Thu, 01 Dec 2022 21:15:16 GMT
Server: Kestrel
Transfer-Encoding: chunked
X-CORRELATION-ID: REDACTED
Content-Type: application/json; charset=utf-8

   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToProviderAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientCoreAsync(String[] scopes, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync(String[] scopes, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
   at Azure.Storage.StorageBearerTokenChallengeAuthorizationPolicy.AuthorizeRequestInternal(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<ProcessAsync>g__ProcessAsyncInner|4_0(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Storage.Blobs.ContainerRestClient.GetPropertiesAsync(Nullable`1 timeout, String leaseId, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.GetPropertiesInternal(BlobRequestConditions conditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.ExistsInternal(Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.ExistsAsync(CancellationToken cancellationToken)
   at NLog.Targets.BlobStorageTarget.CloudBlobService.InitializeContainer(String containerName, CancellationToken cancellationToken)
   at NLog.Targets.BlobStorageTarget.CloudBlobService.InitializeAndCacheBlobAsync(String containerName, String blobName, String contentType, CancellationToken cancellationToken)
`

**Comment by snakefoot** [comment]
There is not enough team-capacity here to help diagnosing user-specific issues in the Azure-cloud.

But if you discover issues in the source-code, that needs to be fixed, then you are very wellcome to point out where to improve.

It seems Azure.Identity still have a long way to go, before reaching the same quality-level as AzureServiceTokenProvider. But [AzureServiceTokenProvider](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/) depends on deprecated [Microsoft.IdentityModel.Clients.ActiveDirectory](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory) that gives dependency-warning (if you care about this).

If you don't have an issue with deprecated dependency-warnings, then I think you should just stick with version 3.2 (And wait with ver 4.x until Azure.Identity is more stable).

But if you have the energy then try to create an issues at the [Azure.Identity](https://github.com/Azure/azure-sdk-for-net/issues)-github-repo, and see if they are in a good mood.

**Comment by Dave-Bronson-Greystone** [comment]
Just adding that we've been encountering the same issue, under the same circumstances, within our apps.  Upgrading from 3.2 to 4.0 has broken the ability to write to Azure blob storage when running in Azure under a managed identity.  I'm going to downgrade to 3.2 and see if things return back to normal.

**Comment by snakefoot** [comment]
Thank you for the feedback about Azure.Identity failing during certain environment-conditions.

It might help others to decide if they want to make the jump to the latest and greatest from Microsoft.

**Comment by Dave-Bronson-Greystone** [comment]
I don't know that Azure.Identity is necessarily the problem.  Those same apps I alluded to above also separately use Azure.Identity + the Azure managed identity to connect to Azure blobs without any trouble.  I similarly have them using the full blob container URI as the only config for the connection.  For example:

`https://namehere.blob.core.windows.net/containernamehere`

Is it possible that the NLog.Extensions.AzureBlobStorage config requirements have changed from 3.2 to 4.0?  I made no modifications to the config after the upgrade to 4.0.

Are `tenantIdentity`, `resourceIdentity`, and `clientIdentity` now required?  The docs are a little weak in describing these settings.  I just need to set aside some time to dig into this more deeply.

NET48
```xml
<target
      name="logAzureBlob"
      xsi:type="AzureBlobStorage"
      layout="${longdate}|${logger}|${uppercase:${level}}|${message} ${exception:format=ToString}"
      container="namehere"
      serviceUri="https://namehere.blob.core.windows.net"
      blobName="Logs/blah.log" />
```

NET7
```json
"logAzureBlob": {
        "type": "AzureBlobStorage",
        "layout": "${longdate}|${logger}|${uppercase:${level}}|${message} ${exception:format=ToString}",
        "container": "namehere",
        "serviceUri": "https://namehere.blob.core.windows.net",
        "blobName": "Logs/blah.log"
      }
```

**Comment by snakefoot** [comment]
> docs are a little weak in describing these settings. I just need to set aside some time to dig into this more deeply.

This is how the properties are mapped to Azure.Identity `DefaultAzureCredentialOptions`:

https://github.com/JDetmar/NLog.Extensions.AzureStorage/blob/master/src/NLog.Extensions.AzureStorage/AzureCredentialHelper.cs

Notice that ResourceIdentity for Blob-Target has this default-value:

https://github.com/JDetmar/NLog.Extensions.AzureStorage/blob/18f8d77cfd9e36b6debdbd6aa5ab00fb87a96c16/src/NLog.Extensions.AzureBlobStorage/BlobStorageTarget.cs#L45

**Comment by snakefoot** [comment]
Thank you for telling about this discovery.

When the next Azure.Identity is released (it also contains lots of connectivity-handshake fixes), then I will update and remove the ResourceIdentity-default-value.

**Comment by snakefoot** [comment]
Created #134 that updates to latest Azure.Identity, and removes ResourceIdentity default value.

**Comment by snakefoot** [comment]
NLog.Extensions.AzureBlobStorage v4.1 is now available - https://www.nuget.org/packages/NLog.Extensions.AzureBlobStorage/

Hopefully it will give a better user experience
