### ISSUE TITLE
The committed block count cannot exceed the maximum limit of 50,000 blocks

### ISSUE THREAD

**Issue by majatu** [JDetmar/NLog.Extensions.AzureStorage#54]
I'm using blob container storage for log files. On 6096 row I've got an exception. Number of writes similar to rows count.

`....Message: System.AggregateException: An error occurred while writing to logger(s). (One or more errors occurred. (One or more errors occurred. (The committed block count cannot exceed the maximum limit of 50,000 blocks.))) ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (The committed block count cannot exceed the maximum limit of 50,000 blocks.)) ---> System.AggregateException: One or more errors occurred. (The committed block count cannot exceed the maximum limit of 50,000 blocks.) ---> Microsoft.WindowsAzure.Storage.StorageException: The committed block count cannot exceed the maximum limit of 50,000 blocks.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.WindowsAzure.Storage.Blob.CloudAppendBlob.AppendBlockAsync(Stream blockData, String contentMD5, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, IProgress1 progressHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.FlushAsync(CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.CommitAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.<Dispose>b__8_0()
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.RunWithoutSynchronizationContext(Action actionToRun)
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Microsoft.WindowsAzure.Storage.Blob.CloudAppendBlob.UploadFromStreamAsyncHelper(Stream source, Nullable1 length, Boolean createNew, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, AggregatingProgressIncrementer progressIncrementer, CancellationToken cancellationToken)
   at NLog.Extensions.AzureStorage.BlobStorageTarget.AppendBlobFromByteArray(String blobName, Byte[] buffer)
   at NLog.Extensions.AzureStorage.BlobStorageTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targetsForLevel, LogEventInfo logEvent, LogFactory factory)
   at NLog.Extensions.Logging.NLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func3 formatter)
   ....`

**Comment by snakefoot** [comment]
One can "only" perform 50000 file-operations. This is okay when log-events are batched together, so one file-operation writes multiple logevents. This requires one to wrap the BlobStorageTarget using AsyncWrapper or BufferingWrapper.

I suggest that you update to the new updated target: https://www.nuget.org/packages/NLog.Extensions.AzureBlobStorage/ (Doesn't require to be wrapped in AsyncWrapper or BufferingWrapper).

**Comment by snakefoot** [comment]
@JDetmar And with #65 then the fix to BlobStorage can be released as ver. 2.3.0

**Comment by snakefoot** [comment]
Updated documentation of how to configure the batching policy:

https://github.com/JDetmar/NLog.Extensions.AzureStorage/blob/master/src/NLog.Extensions.AzureBlobStorage/README.md
