### ISSUE TITLE
Append blob operations are not supported by the emulator

### ISSUE THREAD

**Issue by miscalencu** [JDetmar/NLog.Extensions.AzureStorage#89]
I am trying the **AzureEmulator** example provided at https://github.com/JDetmar/NLog.Extensions.AzureStorage#sample-configuration and I get a "This feature is not currently supported by the Storage Emulator" because:

    at Azure.Storage.Blobs.BlobRestClient.AppendBlob.CreateAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Int64 contentLength, String version, Nullable`1 timeout, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentHash, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String ifTags, String requestId, String blobTagsString, Boolean async, String operationName, CancellationToken cancellationToken)
    at Azure.Storage.Blobs.Specialized.AppendBlobClient.CreateInternal(BlobHttpHeaders httpHeaders, IDictionary`2 metadata, IDictionary`2 tags, AppendBlobRequestConditions conditions, Boolean async, CancellationToken cancellationToken, String operationName)
    at Azure.Storage.Blobs.Specialized.AppendBlobClient.CreateIfNotExistsInternal(BlobHttpHeaders httpHeaders, IDictionary`2 metadata, IDictionary`2 tags, Boolean async, CancellationToken cancellationToken)
    at Azure.Storage.Blobs.Specialized.AppendBlobClient.CreateIfNotExistsAsync(AppendBlobCreateOptions options, CancellationToken cancellationToken)
    at NLog.Targets.BlobStorageTarget.CloudBlobService.InitializeBlob(String blobName, BlobContainerClient blobContainer, String contentType, CancellationToken cancellationToken)
    at NLog.Targets.BlobStorageTarget.CloudBlobService.InitializeAndCacheBlobAsync(String containerName, String blobName, String contentType, CancellationToken cancellationToken)
    2021-01-20 17:16:25.3147 Error AzureBlobStorageTarget: Failed to initialize blob=16.log in container=webapi Exception: Azure.RequestFailedException: This feature is not currently supported by the Storage Emulator.

Append blob operations are not supported by the emulator: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#differences-for-table-storage.

Am I missing something in the configuration or something changed in the meantime?

**Comment by snakefoot** [comment]
@miscalencu If you have an elegant way of making it work with the emulator please tell. But right now the work-around seems to be:
1. Read the existing blob into memory-buffer
2. Append the additional bytes to the memory-buffer
3. Rewrite the memory-buffer and overwrite the blob

This doesn't seem very optimal compared to just appending. Maybe try this emulator https://github.com/azure/azurite ?

**Comment by miscalencu** [comment]
I understand. I was just asking as a user, as your examples in the readme file all use the emulator and they don't actually work.

**Comment by snakefoot** [comment]
Good point. Will remove the emulator example and update the docs about blob-target using append that requires the azurite-emulator


Sent from my Sony Xperia


---- George Miscalencu wrote ----


I understand. I was just asking as a user, as your examples in the readme file all use the emulator and they don't actually work.

**Comment by snakefoot** [comment]
Created pull-request for updating the wiki: #88

https://github.com/snakefoot/NLog.Extensions.AzureStorage/blob/master/src/NLog.Extensions.AzureBlobStorage/README.md#azure-blob-storage-emulator
